version: '3.8'

services:
  # FastAPI Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      # Alternative: dockerfile: Dockerfile.multistage (if permission issues occur)
    network_mode: host
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      # Mount server code for development
      - ./server:/app
      # Exclude Python cache and virtual environments
      - /app/__pycache__
      - /app/.venv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Next.js Frontend UI
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
      # Alternative: dockerfile: Dockerfile.multistage (if permission issues occur)
    network_mode: host
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      # Mount UI code for development
      - ./ui:/app
      # Exclude node_modules and build artifacts
      - /app/node_modules
      - /app/.next
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped

  # Optional: Redis for caching/session management
  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  redis-data:
    driver: local
