# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'numpy.typing',
        'numpy._typing',
        'numpy.typing._array_like',
        'numpy.typing._dtype_like',
        'numpy.typing._nested_sequence',
        'numpy.typing._char_codes',
        'numpy.typing._nbit',
        'numpy.typing._shape',
        'numpy.typing._generic_alias',
        'cv2',
        'aiortc',
        'aiortc.codecs',
        'aiortc.contrib',
        'aiortc.mediastreams',
        'aiortc.rtcpeerconnection',
        'aiortc.rtcrtpsender',
        'aiortc.rtcrtpreceiver',
        'aiortc.rtcdatachannel',
        'aiortc.rtcicetransport',
        'aiortc.rtcdtlstransport',
        'aiortc.rtcsctptransport',
        'aiortc.rtcsessiondescription',
        'aiortc.contrib.media',
        'av',
        'av.video',
        'av.audio',
        'av.container',
        'av.codec',
        'av.frame',
        'av.packet',
        'av.stream',
        'netifaces',
        'aiosqlite',
        'click',
        'httpx',
        'fastapi',
        'uvicorn',
        'pydantic',
        'loguru',
        'skimage',
        'sklearn',
        'scipy',
        'scipy.ndimage',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)